'email'=>'Email',
'email_status0'=>'NOT Verified',
'email_status1'=>'Verified',
'email_status2'=>'Waiting Code',
'set_email'=>'Set Email',
'verify_email'=>'Verify Email',
'verify_code'=>'Verify Code',